#pragma once


enum class eLOCAL_CLIENT_CMD{
	REG_CAR_HEANDLE = 144,
	GET_HEANDLE_CAR_OF_POOL = 130,
	COMPARE_HEANDLE_CAR = 120,
	GOOD_HEANDLE_CAR = 110,
};

enum class EDESIGN_COMMAND
{
	CMD_SPAWN_VEHICLE = 301,
	CMD_VEHICLE_NEW_POSSITIONS = 302,
	CMD_VEHICLE_NEW_COLOR = 303,
};
