#pragma once


enum eHeaderPackage
{
	// TOOLS
	RPC_ADMINS_CMD = -18,
	RPC_ADMINS_CMD_PRINT_DATA_BASE_CAR = -3,

	// PLAYER
	RPC_PLAYER_ACTOR_POSSITIONS = 7,

	// VEHICLE
	RPC_SERVER_VEHICLE_CAR_POSSITIONS = 300,
	RPC_VEHICLE_ID_DEATCH = 302,
};
